"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import { Toaster } from "react-hot-toast";
import { Bars3Icon } from "@heroicons/react/24/outline";
import { useState, useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function LayoutContent({ children }: { children: React.ReactNode }) {
  const [isOpen, setIsOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  const toggle = () => setIsOpen(!isOpen);

  // Detectar si es mobile y abrir sidebar por defecto en desktop
  useEffect(() => {
    const checkMobile = () => {
      const mobile = window.innerWidth < 768;
      setIsMobile(mobile);
      if (!mobile) {
        setIsOpen(true); // Abrir por defecto en desktop
      }
    };
    
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  return (
    <div className="min-h-screen bg-gray-50">
      <Toaster 
        position="top-right"
        toastOptions={{
          duration: 4000,
          style: {
            background: '#363636',
            color: '#fff',
          },
        }}
      />
      
      <div className="h-screen flex bg-gray-50">
        {/* Sidebar */}
        <Sidebar isOpen={isOpen} onToggle={toggle} />
        
        {/* Main Content */}
        <div className={`
          flex-1 flex flex-col min-h-screen
          transition-all duration-300 ease-in-out
          ${!isMobile && isOpen ? 'ml-0' : ''}
        `}>
          {/* Header con botón hamburguesa */}
          <header className="bg-white border-b border-gray-200 px-4 py-3 flex items-center sticky top-0 z-30">
            <button
              onClick={toggle}
              className="p-2 hover:bg-gray-100 rounded-md transition-colors mr-3"
              aria-label={isOpen ? "Cerrar menú" : "Abrir menú"}
            >
              <Bars3Icon className="w-6 h-6 text-gray-600" />
            </button>
            <h1 className="text-lg font-semibold text-gray-900">
              {isMobile ? "WhatsApp Web" : "Dashboard"}
            </h1>
          </header>
          
          {/* Contenido principal */}
          <main className="flex-1 overflow-auto">
            <div className="p-6">
              {children}
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <title>WhatsApp Messenger</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}